version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(pip)"
    groups:
      python:
        patterns:
          - "*"

  - package-ecosystem: nix
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(nix)"
    groups:
      nix-inputs:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(actions)"
    groups:
      actions:
        patterns:
          - "*"